name: Unzip Files

on: 
  push:
    branches:
      - main  # Customize the branch if needed

jobs:
  unzip:
    runs-on: ubuntu-latest  # Or another suitable environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip files
        uses: montudor/action-zip@v1
        with:
          args: 'unzip path/to/your/zipfile.zip -d path/to/extract/to' 
